### ISSUE TITLE
print function

### ISSUE THREAD

**Issue by RichardSieg** [sebasguts/PyNormaliz#11]
print all already computed objects of a cone

**Comment by RichardSieg** [comment]
Write a .print() function or override __str__ ?

**Comment by RichardSieg** [comment]
I would like to create a python list of all available ConeProperties and then just run through them and print if available. Is that manageable in the Nmz module?

**Comment by sebasguts** [comment]
I would not call it `print`, but maybe `list_computed_properties` or something, since `print` is already build-in in python and calls `__str__`.
Maybe there also should be two methods. One which simply prints the information somehow nicely to `stdout`, and another one which produces a `dict` in the sense of
```
{ 'HilbertBasis' : True }
```

**Comment by sebasguts** [comment]
> I would like to create a python list of all available ConeProperties and then just run through them and print if available. Is that manageable in the Nmz module?

Yes, with some drawback. You will not only get the output properties, but also the compute flags. Is that okay?

**Comment by RichardSieg** [comment]
That would be okay. Maybe the best solution is having a function in the module that out of the ConeProperty enum creates a python string list. Then in PyNormaliz.py we just run over the list. If IsComputed is True we print it. WHat do you think?

**Comment by sebasguts** [comment]
Yup, that what I was thinking. I will add this to the C++-module, but it might take some time, since there is a bit to care to do it compatible for python2 and python3. I would like to use this for #12 too, is there a way to separate the enums in libNormaliz?
One idea would be to add a dummy `ConeProperty` which stands between the ones that can be computed and the ones that are input-only. Also, we could get rid of a lof of cases in `NmzResult`.

**Comment by RichardSieg** [comment]
Perfect! I just talked to Prof Bruns about this: In cone_property.cpp should be a function (or we create one) that gives all ConeProperties which are not compute options. Then we just take that function and make a python list out of it. He will write a mail concerning this.

**Comment by sebasguts** [comment]
So, the list is there. Have fun with it.
